---
title: "data_viz_meg"
format: html
---

Load Libraries
```{r}
library(tidyverse)
library(dplyr)
library(tmap)
```

Load data and color pal
```{r}
out_enriched_v1 <- readRDS("/capstone/netzerohydro/data/out_enriched/out_enriched_v1.rds")

str(out_enriched_v1)

# Color Palette 
connectivity_cat_pal <- c("cascade_classic" = "#0e5faf",
                          "cascade1" = "#67A9CF",
                          "cascade2+" = "#D1E5F0",
                          "has_upstream_dam" = "#f7d35d",
                          "has_downstream_dam" = "#EF8A62", 
                          "undammed" = "#B2182B")

```

## MCDA Model Histogram 
```{r}
# MCDA model histogram ----------------------------------------------------------
mcda_histogram <- out_enriched_v1 %>% 
  filter(dam_type == "future") %>% 
  ggplot() + 
  geom_histogram(aes(x = wsm_scores, fill = connectivity_category)) + 
  scale_fill_manual(values = connectivity_cat_pal) + 
  facet_wrap(~threshold_k) +
  theme_light() + 
  labs(x = "WSM Scores", 
       y = "Count", 
       title = "MCDA Scores") 

#ggsave("~/MEDS/capstone/figs/mcda_histogram.png", plot = mcda_histogram, width = 10, height = 7)
```

## Connectivity catagories 
```{r}
# Bar plot of connectivity catagories  -----------------------------------------
conn_cat_barplot <- out_enriched_v1 %>% 
  filter(dam_type == "future") %>% 
  group_by(connectivity_category, threshold_k) %>% 
  summarise(count = n(), 
            .groups = 'drop') %>% 
  ggplot() + 
  geom_col(aes(x = connectivity_category, y = count, fill = connectivity_category)) + 
  scale_fill_manual(values = connectivity_cat_pal) + 
  facet_wrap(~threshold_k) +
  theme_light() + 
  labs(x = "Connectivity", 
       y = "Count", 
       title = "Connectivity Categories Across Thresholds") + 
  theme(axis.text.x = element_blank())


#ggsave("~/MEDS/capstone/figs/conn_cat_barplot.png", plot = conn_cat_barplot, width = 10, height = 7)
```


## Countries 

List of top 10 
```{r}
# Counties have the most amount of future dams 
out_enriched_v1 %>% 
  filter(dam_type == "future" & threshold_k == 'Inf') %>% 
  st_drop_geometry() %>% 
  group_by(country) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  head(10) %>% 
  kable(caption = "Number of Future Dams per Country", col.names = c("Country", "Count")) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F)

```


Barplot 
```{r}

# top 10 counties - highest number of future dams 
top_ten_countries <- out_enriched_v1 %>% 
  filter(dam_type == "future" & threshold_k == 'Inf') %>% 
  st_drop_geometry() %>% 
  group_by(country) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  head(10) %>% 
  pull(country)

top_ten_countries


# Top 10 countries dam categories 
county_dam_barplot <- out_enriched_v1 %>% 
  filter(dam_type == "future" & 
           country %in% top_ten_countries) %>% 
  st_drop_geometry() %>% 
  ggplot() + 
  geom_bar(aes(y = fct_rev(fct_infreq(country)),fill = connectivity_category)) + 
  scale_fill_manual(values = connectivity_cat_pal) + 
  facet_wrap(~threshold_k) +
  theme_light() + 
  labs(x = "Count", 
       y = "", 
       title = "Countries with the Top Ten Most Future Dams") 

#ggsave("~/MEDS/capstone/figs/county_dam_barplot.png", plot = county_dam_barplot, width = 10, height = 7)

```

Map 
```{r}
# Map 
# Get county polygons 
world_countries <- read_sf("/capstone/netzerohydro/data/raw/World_Countries_Generalized_Shapefile") %>% 
  clean_names() %>% 
  st_transform(crs = target_crs)
ggplot(world_countries) + # Make sure polgons are good 
  geom_sf()
# Merge polygons to dam df 
county_dam <- out_enriched_v1 %>% 
  filter(dam_type == "future") %>% 
  st_drop_geometry() %>% 
  group_by(country, threshold_k) %>% 
  summarise(count = n(), .groups = 'drop') 

dim(county_dam) # 552   3... 92 countries 
dim(world_countries) # 251   5 
# Join country + dam count with country 
county_dam_geom <- full_join(county_dam, world_countries, by = join_by(country))
 
# Make spatial 
county_dam_geom <- county_dam_geom %>% 
  st_as_sf() %>% 
  st_transform(crs = target_crs)

# Map - looking off 
county_dam_geom %>% 
  ggplot() + 
  geom_sf(aes(fill = count)) + 
  theme_void() + 
  labs(fill = "Number of\nFuture Dams")


```


## Capacity 
**Problem: outliers are throwing it off**

Histogram
```{r}
# Histogram 
out_enriched_v1 %>% 
  filter(dam_type == "future") %>% 
  ggplot() + 
  geom_histogram(aes(x = capacity_mw, fill = connectivity_category)) + 
  scale_fill_manual(values = connectivity_cat_pal) + 
  #coord_cartesian(xlim = c(0, 8000)) +
  facet_wrap(~threshold_k) +
  theme_light() + 
  labs(x = "Capacity", 
       y = "Count", 
       title = "Capacity") 
```

boxplot / violin plot 
```{r}
# boxplot / violin plot 
out_enriched_v1 %>% 
  filter(dam_type == "future") %>% 
  ggplot() + 
  geom_boxplot(aes(x = capacity_mw, y = connectivity_category)) + 
  #scale_fill_manual(values = connectivity_cat_pal) + 
  #coord_cartesian(xlim = c(0, 5000)) +
  facet_wrap(~threshold_k) +
  theme_light() + 
  labs(x = "Capacity", 
       y = "connectivity_category", 
       title = "Capacity") 


```


Point - CSI and capacity 
```{r}
# Point 
out_enriched_v1 %>% 
  filter(dam_type == "future" & threshold_k == 'Inf') %>% 
  ggplot() + 
  geom_point(aes(x = capacity_mw, y = csi, col = connectivity_category)) + 
  scale_color_manual(values = connectivity_cat_pal) + 
  #coord_cartesian(xlim = c(0, 5000)) +
  theme_light() + 
  labs(x = "Capacity", 
       y = "CSI", 
       title = "Capacity VS CSI") 
```



