---
title: "wsm_function_testing"
format: html
---
## Fake dataset 

Building a fake dataset that I can predict the outcomes 
```{r}
dam_df <- data.frame(
  dam_id = c("2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010"), 
  bb_id = c(1, 1, 1, 2, 2, 2, 3, 3, 4, 4), # trunk id 
  min_distance_upstream_km = c(NA, 10, 30, NA, 3, NA, 30, 200, NA, 2),  
  min_distance_downstream_km = c(20, 10, NA, NA, 15, 30, 100, 10, NA, 14), 
  # connectivity indexes 
  cascade_status = c(0,1,0,NA,1,0,0,0,NA,1), 
  csi = c(0.40, 0.10, 0.22, 0.90, 0.12, 0.25, 0.81, 0.70, 0.95, 0.07),
  # fatal flaws 
  in_protected_area = c(0,1,1,0,0,1,1,1,0,0) # CHANGED to have 1 = good (no PA) and 0 = bad (inside PA)... WAS c(1,0,0,1,1,0,0,0,1,1) 
)


# upsteam, downstream, cascade 
dam_df <- dam_df %>% 
  mutate(connectivity_category = case_when(
    min_distance_upstream_km <= 15 & min_distance_downstream_km <= 15 ~ "cascade", 
    is.na(min_distance_upstream_km) & is.na(min_distance_downstream_km) ~ "FFR",
    is.na(min_distance_upstream_km) & min_distance_downstream_km <= 50 | 
      min_distance_upstream_km > 50 & min_distance_downstream_km <= 50 ~ "upstream", 
    min_distance_upstream_km <= 50 & is.na(min_distance_downstream_km) | 
      min_distance_upstream_km <= 50 & min_distance_downstream_km > 50 ~ "downstream", 
    TRUE ~ NA
  ))


# Change the connectivity_category to numbers 
dam_df <- dam_df %>% 
  mutate(connectivity_category_num  = case_when(
    connectivity_category == "cascade" ~ 5, 
    connectivity_category == "upstream" ~ 3, 
    connectivity_category == "downstream" ~ 3, 
    connectivity_category == "ffr" ~ 1, 
    TRUE ~ 1
    ))


dam_df

```

Trying function on fake data 
```{r}

criteria <- c("csi", "connectivity_category_num", "in_protected_area")

criteria_weights <- c(csi = 0.5, connectivity_category_num = 0.3, in_protected_area = 0.2)

criteria_type <- c(csi = "nonbeneficial", connectivity_category_num = "beneficial", in_protected_area = "beneficial")


wsm_function(dataset = dam_df, 
     criteria = criteria, 
     criteria_weights = criteria_weights, 
     criteria_type = criteria_type)
```


## Real dataset 

`reach_df_one` from trunk_id_exploration 

`future_dams_flagged` from fatal-flaws -> protected areas

```{r}
# --- JOINING dam data to PA data ---  

# future_dams_flagged <- future_dams_flagged %>% st_drop_geometry()
# future_dams_flagged$dam_id <- as.character(future_dams_flagged$dam_id)
join <- left_join(reach_df_one, future_dams_flagged, by = 'dam_id')


# --- Adding a connectivity catagory ---
join_trial <- join %>%
  mutate(connectivity_category = case_when(
    
    # (1) Both within 50km
    min_distance_upstream_km <= 250 & min_distance_downstream_km <= 250 ~ "cascade",
    
    # (2) No dams in either direction OR both further than 200km
    (is.na(min_distance_upstream_km) | min_distance_upstream_km > 250) &
      (is.na(min_distance_downstream_km) | min_distance_downstream_km > 250) ~ "FFR",
    
    # (3) Upstream dam within 200km, no downstream or downstream > 200km
    min_distance_upstream_km <= 250 &
      (is.na(min_distance_downstream_km) | min_distance_downstream_km > 250) ~ "downstream",
    
    # (4) Downstream dam within 200km, no upstream or upstream > 200km
    min_distance_downstream_km <= 250 &
      (is.na(min_distance_upstream_km) | min_distance_upstream_km > 250) ~ "upstream",
    
    TRUE ~ NA
  ))


# Change the connectivity_category to numbers 
join_trial <- join_trial %>% 
  mutate(connectivity_category_num  = case_when(
    connectivity_category == "cascade" ~ 5, 
    connectivity_category == "upstream" ~ 2, 
    connectivity_category == "downstream" ~ 2, 
    connectivity_category == "FFR" ~ 1, 
    TRUE ~ 1
    ))



join_trial <- join_trial %>%
  mutate(
    in_protected_area_num = case_when(
      in_protected_area == FALSE ~ 1, # no PA, 1 = "good"
      in_protected_area == TRUE ~ 0, # inside PA, 0 = bad 
      TRUE ~ NA
    )
  )

```

Using the function 
```{r}
criteria <- c('csi', 'connectivity_category_num', 'in_protected_area_num')

criteria_weights <- c(csi = 0.4, connectivity_category_num = 0.55, in_protected_area_num = 0.05)

criteria_type <- c(csi = "nonbeneficial", # Lower number = better 
                       connectivity_category_num = "beneficial", # Higher number = better 
                       in_protected_area_num = "beneficial")


results <- wsm_function(dataset = join_trial, 
     criteria = criteria, 
     criteria_weights = criteria_weights, 
     criteria_type = criteria_type)

results

results_filtered <- results %>% 
  select(c(dam_id, csi, capacity_mw, in_protected_area,in_protected_area_num, connectivity_category, connectivity_category_num, wsm_scores, score_letter))


count <- results_filtered %>% 
  group_by(connectivity_category, score_letter) %>% 
  summarise(count = n(), .groups = "drop") 

averages <- results_filtered %>% 
  group_by(connectivity_category, score_letter) %>% 
  summarise(avg_wsm = mean(wsm_scores), 
            avg_csi = mean(csi), 
            avg_PA = mean(in_protected_area_num),
            .groups = "drop") 

left_join(count, averages, by = c("connectivity_category", "score_letter"))

```


## Trying another Dataset 
Lucian's new cascade level data = `raf_data`
`future_dams_flagged` = Aakritis dataset 

```{r}
# Load data 
raf_data <- readRDS("../../../../../capstone/netzerohydro/data/cleaned_v1/raf_presentation_df.rds")

east_as_basin_sf <- read_sf("../../../../../capstone/netzerohydro/data/raw/hybas_as_lev02_v1c/hybas_as_lev02_v1c.shp") |>
  janitor::clean_names() %>% 
  filter(hybas_id == 4020015090) %>% 
  st_transform(crs = 4326)


# Fix dam_id 
future_dams_flagged$dam_id <- as.character(future_dams_flagged$dam_id)

# Join PA with dam data 
east_as_pa <- left_join(raf_data, future_dams_flagged, by = 'dam_id')

# Fix the Data 
east_as_pa <- east_as_pa %>%
  mutate(connectivity_category = case_when(
    cascade_level >= 1 ~ "cascade",
    # (2) No dams in either direction OR both further than 200km
    (is.na(min_distance_upstream_km) | min_distance_upstream_km > 70) &
      (is.na(min_distance_downstream_km) | min_distance_downstream_km > 70) ~ "FFR",
    # (3) Upstream dam within 200km, no downstream or downstream > 200km
    min_distance_upstream_km <= 70 &
      (is.na(min_distance_downstream_km) | min_distance_downstream_km > 70) ~ "downstream",
    # (4) Downstream dam within 200km, no upstream or upstream > 200km
    min_distance_downstream_km <= 70 &
      (is.na(min_distance_upstream_km) | min_distance_upstream_km > 70) ~ "upstream",
    TRUE ~ NA
  )) %>% 
  mutate(connectivity_category_num = case_when(
    connectivity_category == "cascade" & cascade_level == 1 ~ 7, 
    connectivity_category == "cascade" & cascade_level == 2 ~ 6,
    connectivity_category == "cascade" & cascade_level >= 3 ~ 5, 
    connectivity_category == "upstream" ~ 3,
    connectivity_category == "downstream" ~ 2.99,
    connectivity_category == "FFR" ~ 1,
  )) %>% 
  mutate(in_pa_num = ifelse(in_protected_area == FALSE, 1, 0)) %>%  # 1 = No in PA (good)
  #st_drop_geometry() %>% 
  filter(dam_type == "future")
  
```

Examine output 
```{r}
east_as_pa %>% 
  filter(connectivity_category_num == 6)
```


```{r}

criteria <- c('csi', 'connectivity_category_num', 'in_pa_num')

criteria_weights <- c(csi = 0.4, connectivity_category_num = 0.5, in_pa_num = 0.1)

criteria_type <- c(csi = "nonbeneficial", # Lower number = better 
                       connectivity_category_num = "beneficial", # Higher number = better 
                       in_pa_num = "beneficial")


results <- wsm_function(dataset = east_as_pa, 
     criteria = criteria, 
     criteria_weights = criteria_weights, 
     criteria_type = criteria_type)

results

```

```{r}
# Create a weight label 
weight_label = paste0(names(criteria_weights), ": ", criteria_weights)
weight_label <- paste(weight_label, collapse = "\n")
weight_label1 <- paste0("<b>", "Criteria Weights:\n", "</b><br>", weight_label)
weight_label2 <- paste0("Criteria Weights:\n", weight_label)

```

```{r}
# Factor the connectivity_category_num 
results$connectivity_category_num <- factor(results$connectivity_category_num, levels = c(7,6,5,3,2.99,1), labels = c('Cascade1', 'Cascade2', 'Cascade3+', 'Upstream', 'Downstream', "FFR"))

# Histogram 
hist <- results %>% 
  #filter(connectivity_category == "cascade") %>% 
  ggplot() +
  geom_histogram(aes(wsm_scores, fill = connectivity_category_num)) + 
  theme_light() + 
  #scale_fill_manual(values = c("darkorange1", "darkolivegreen2", "royalblue1", "orchid3")) +
  labs(title = "Weight Sum Model (WSM) Scrores\nof Southeast Asia Future Dams", 
       x = "WSM Scores", 
       y = "Count", 
       fill = "Connectivity Catagory", 
       caption = weight_label2) 

hist

# ggsave(filename = here::here("plots","wms_hist_cat.png"), # Will created directory if not already there
#   plot = hist,
#   height = 5,
#   width = 7)

# Table
results %>% 
  group_by(score_letter) %>% 
  summarise(count = n(), 
            avg_scores = mean(wsm_scores, na.rm = TRUE), 
            max_scores = max(wsm_scores, na.rm = TRUE), 
            min_scores = min(wsm_scores, na.rm = TRUE), 
            median_scores = median(wsm_scores, na.rm = TRUE), 
            avg_csi = mean(csi, na.rm = TRUE)) %>% 
  kableExtra::kbl(digits = 3) %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"))



```

```{r}
# map
library(tmap)
library(sf)

# Make it sf and 
results_sf <- st_as_sf(results, crs = 4326)

# Check CRS 
st_crs(results_sf) == st_crs(east_as_basin_sf)
results_sf <- st_set_crs(results_sf, 4326) 


# Plot 
# GGplot 
wms_ggmap <- ggplot() +
  geom_sf(data = east_as_basin_sf, fill = NA, color = "black", alpha = 0.5) +
  geom_sf(data = results_sf, aes(color = wsm_scores, 
                                 text = paste0(
      "<b>Dam_ID: ", dam_id, "</b><br>", 
      "<b>CSI: </b>", csi, "<br>", 
      "<b>Connectivity Category: </b>", connectivity_category_num, "<br>", 
      "<b>In a PA: </b>", in_protected_area, "<br>",
      "<b>Capacity: </b>", capacity_mw, "mw"
    ))) +
  scale_color_gradientn(
    colors = colorRampPalette(c("#0f31bc", "#77d613", "orange"))(100),
    name = "WSM Scores"
  ) +
  #theme_minimal() + 
  theme_void() + 
  labs(title = "Weighted Sum Model Scores for Future Dams in Southeast Asia") + 
  annotate(geom = "text", x = 115, y = 5, label = weight_label2, size = 2, hjust = 0)

wms_ggmap_interactive <- ggplotly(wms_ggmap, 
         tooltip = "text" # inside of hover tool tip
         )

wms_ggmap_interactive

#htmlwidgets::saveWidget(
  #ggplotly(wms_ggmap_interactive, tooltip = "text"),
  #file = here::here("plots", "wms_ggmap_interactive4.html")
#)

```


